# Generated by Django 2.1.7 on 2021-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # 添加atomic
    dependencies = [
        ('mainapp', '0004_auto_20210426_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='8f09a178195e470d8fa323ac82b9ceb0', primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='last_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后变更时间'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='story_type',
            field=models.IntegerField(choices=[(0, '自营'), (1, '第三方')], db_column='type_', verbose_name='类型'),
        ),
        migrations.AlterModelTable(
            name='catetypeentity',
            table='t_category',
        ),
    ]
