# Generated by Django 2.1.7 on 2021-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # 添加atomic
    dependencies = [
        ('mainapp', '0005_auto_20210426_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='430011d213584c38a4c53870bb02f79e', primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.AlterModelTable(
            name='catetypeentity',
            table='app_category',
        ),
    ]
