# Generated by Django 2.1.7 on 2021-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # 添加atomic
    dependencies = [
        ('mainapp', '0006_auto_20210426_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='1359bc3435d245b884ef4cdec95347ce', primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.AlterModelTable(
            name='catetypeentity',
            table='t_category',
        ),
    ]
