# Generated by Django 2.1.7 on 2021-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210426_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentity',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='store', verbose_name='LOGO', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_height',
            field=models.IntegerField(null=True, verbose_name='LOGO宽'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_width',
            field=models.IntegerField(null=True, verbose_name='LOGO宽'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='是否开业'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='5461b26f9ef341b2b17ea06e8fb1612a', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
