# Generated by Django 2.1.7 on 2021-04-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210426_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='8e5c09b53a16402e9b5cacecfd247198', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
