# Generated by Django 2.1.7 on 2021-04-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210427_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitCartEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1, verbose_name='数量')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CartEntity', verbose_name='购物车编号')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FruitEntity', verbose_name='水果名')),
            ],
            options={
                'verbose_name': '购物车详细表',
                'verbose_name_plural': '购物车详细表',
                'db_table': 't_fruit_cart',
            },
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='52b706bc53a84eca9e72ef6f35785e5e', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
