# Generated by Django 2.1.7 on 2021-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210428_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(db_table='t_collect', related_name='fruits', to='mainapp.UserEntity', verbose_name='收藏用户列表'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='d62bf7b9c0374f6a8bff982c9339ded8', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
