# Generated by Django 2.1.7 on 2021-04-28 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210428_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('order_num', models.IntegerField(default=1, verbose_name='序号')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 't_tag',
                'ordering': ['-order_num'],
            },
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='mainapp.CateTypeEntity'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='d47ac332401a4369969105a17343644e', primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='tags',
            field=models.ManyToManyField(db_table='t_fruit_tags', related_name='fruits', to='mainapp.TagEntity', verbose_name='所有标签'),
        ),
    ]
