# Generated by Django 2.1.7 on 2021-04-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210428_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='口令'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='mainapp.CateTypeEntity'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='源产地'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='t_fruit_tags', null=True, related_name='fruits', to='mainapp.TagEntity', verbose_name='所有标签'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='t_collect', null=True, related_name='fruits', to='mainapp.UserEntity', verbose_name='收藏用户列表'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='7030abf0513b404cabfb2d5d3973994d', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
